// app/layout.tsx
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/providers/tanstack-query-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { HeaderProvider } from "@/modules/blogs/components/global-header/context/HeaderContext";

export const metadata: Metadata = {
  title: "BlogKit",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} ${inter.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <HeaderProvider>
              <SessionProvider>{children}</SessionProvider>
            </HeaderProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
